import java.util.List;
import java.util.stream.Collectors;

import static java.util.Comparator.comparing;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public List<Model> sortWithName(List<Model> models) {
        return models.stream()
                .sorted(comparing(model -> model.name))
                .collect(Collectors.toList());
    }
}
