/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification

class LibraryTest extends Specification {
    def "sortWithName success"() {
        setup:
        def lib = new Library()
        def models = [
                new Model(24, "Nougat"),
                new Model(11, "Honeycomb"),
                new Model(8, "Eclair"),
                new Model(19, "KitKat"),
                new Model(4, "Cupcake"),
        ]

        when:
        def result = lib.sortWithName(models)

        then:
        result == [
                new Model(4, "Cupcake"),
                new Model(8, "Eclair"),
                new Model(11, "Honeycomb"),
                new Model(19, "KitKat"),
                new Model(24, "Nougat"),
        ]
    }
}
